## Legacy Bun test configuration (kept for compatibility)
[test]
# Use a DOM-like environment so React component tests work from repo root
environment = "happy-dom"

# Keep default discovery; each package may also have its own bunfig
# Retained so legacy Bun-based workflows still get a DOM-like environment
[test]

# always enable coverage
coverage = true
coverageThreshold = 0.95
coverageReporter  = ["text", "lcov"]
coverageDir = "coverage"