import { defineConfig } from 'vite-plus';

export default defineConfig({
  resolve: {
    alias: {
      '@sentry/react-router': new URL('app/core/__mocks__/@sentry/react-router.ts', import.meta.url)
        .pathname,
      '@microlabs/otel-cf-workers': new URL(
        'app/apex/__mocks__/@microlabs/otel-cf-workers.ts',
        import.meta.url,
      ).pathname,
      '@hono/otel': new URL('app/apex/__mocks__/@hono/otel.ts', import.meta.url).pathname,
    },
  },
  test: {
    coverage: {
      exclude: [
        '**/+types/**',
        '**/*.d.ts',
        '**/*.test.{ts,tsx}',
        '**/node_modules/**',
        '**/build/**',
        '**/dist/**',
        '**/__mocks__/**',
        '**/public/**',
        '**/.react-router/**',
        '**/*.css',
        '**/*.svg',
        '**/workers/**',
        '**/test-setup.ts',
        '**/locales/**',
        '**/zod.ts',
        '**/react-router.config.ts',
        '**/coverage/**',
        '**/.next/**',
        '**/.open-next/**',
        '**/next.config.ts',
        '**/open-next.config.ts',
        '**/app/core/**',
        '**/com/core/**',
        '**/org/core/**',
        '**/dev/core/**',
        '**/app/news/**',
        '**/com/news/**',
        '**/org/news/**',
        '**/app/docs/**',
        '**/com/docs/**',
        '**/org/docs/**',
        '**/app/help/**',
        '**/com/help/**',
        '**/org/help/**',
        '**/apex/src/root-redirect.ts',
        '**/apex/src/footer.tsx',
        '**/apex/src/routes.ts',
        '**/apex/src/app.tsx',
        '**/apex/src/index.tsx',
        '**/apex/src/otel.ts',
        '**/apex/src/renderer.tsx',
        '**/apex/html/index.ts',
        '**/apex/middleware/index.ts',
        '**/apex/routes/index.ts',
        '**/src/i18n/**',
        '**/src/app/**',
        'shared/cloudflare/**',
      ],
      include: ['**/*.{ts,tsx,js,jsx}'],
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html'],
      thresholds: {
        branches: 98,
        functions: 98,
        lines: 98,
        statements: 98,
      },
    },
    deps: {
      interopDefault: true,
    },
    environment: 'happy-dom',
    globals: true,
    include: [
      'app/**/*.test.{ts,tsx}',
      'com/**/*.test.{ts,tsx}',
      'dev/**/*.test.{ts,tsx}',
      'org/**/*.test.{ts,tsx}',
      'net/**/*.test.{ts,tsx}',
      'shared/**/*.test.{ts,tsx}',
      'test/**/*.test.{ts,tsx}',
    ],
    setupFiles: ['./vitest.setup.ts'],
  },
});
