// Generated by React Router

import "react-router";

declare module "react-router" {
	interface Register {
		pages: Pages;
		routeFiles: RouteFiles;
	}
}

type Pages = {
	"/": {
		params: {};
	};
	"/about/:name": {
		params: {
			name: string;
		};
	};
	"/blog": {
		params: {};
	};
	"/blog/:name": {
		params: {
			name: string;
		};
	};
	"/merch/*": {
		params: {
			"*": string;
		};
	};
};

type RouteFiles = {
	"root.tsx": {
		id: "root";
		page: "/" | "/about/:name" | "/blog" | "/blog/:name" | "/merch/*";
	};
	"routes/_layout.tsx": {
		id: "routes/_layout";
		page: "/" | "/about/:name" | "/blog" | "/blog/:name" | "/merch/*";
	};
	"routes/_index.tsx": {
		id: "routes/_index";
		page: "/";
	};
	"routes/about/[name].tsx": {
		id: "routes/about/[name]";
		page: "/about/:name";
	};
	"routes/blog/index.tsx": {
		id: "routes/blog/index";
		page: "/blog";
	};
	"routes/blog/(content)/[name].tsx": {
		id: "routes/blog/(content)/[name]";
		page: "/blog/:name";
	};
	"routes/merch/[...slug].tsx": {
		id: "routes/merch/[...slug]";
		page: "/merch/*";
	};
};
